name: Music Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Convert format
        run: |
          echo `ls`
          docker run -v .:/workspace benzoin96485/musescore:v1 mscore farewell/farewell.mscx -o farewell.mp3
          docker run -v .:/workspace benzoin96485/musescore:v1 mscore farewell/farewell.mscx -o farewell.pdf
          docker run -v .:/workspace benzoin96485/musescore:v1 mscore farewell/farewell.mscx -o farewell.mid
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: |
            ./farewell.mp3
            ./farewell.pdf
            ./farewell.mid
            ./farewell/farewell.mscx
          body: |
            I released a new song called Farewell.
    
          
